apiVersion: apps/v1
kind: Deployment
metadata:
  name: confused
  namespace: trouble1
spec:
  selector:
    matchLabels:
      app: whatever
  replicas: 1
  template:
    metadata:
      labels:
        app: whatever
    spec:
      containers:
        - name: something
          image: nginx:1.19.0
