apiVersion: apps/v1
kind: Deployment
metadata:
  name: wegotan
  namespace: trouble1
spec:
  selector:
    matchLabels:
      app: ooh
  replicas: 1
  template:
    metadata:
      labels:
        app: ooh
    spec:
      containers:
        - name: much
          image: centos:7
          command:
            - sh
            - '-c'
            - "sleep 5 && yes | tr \\n x | head -c 500m | grep n && sleep 1000"
          resources:
            limits:
              memory: 400M
        - name: shell
          image: centos:7
          command:
            - sh
            - '-c'
            - sleep 1000
