---
# Source: chaoskube/templates/deployment.yaml
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: RELEASE-NAME-chaoskube
  labels:
    app.kubernetes.io/name: chaoskube
    app.kubernetes.io/managed-by: "Helm"
    app.kubernetes.io/instance: "RELEASE-NAME"
    helm.sh/chart: chaoskube-3.1.0
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: chaoskube
      app.kubernetes.io/instance: RELEASE-NAME
  template:
    metadata:
      labels:
        app.kubernetes.io/name: chaoskube
        app.kubernetes.io/managed-by: "Helm"
        app.kubernetes.io/instance: "RELEASE-NAME"
        helm.sh/chart: chaoskube-3.1.0
    spec:
      containers:
        - name: chaoskube
          image: registry.cn-hangzhou.aliyuncs.com/kubeapps/quay-chaoskube:v0.14.0
          args:
            - --interval=10m
            - --labels=
            - --annotations=
            - --namespaces=
            - --excluded-weekdays=
            - --excluded-times-of-day=
            - --excluded-days-of-year=
            - --timezone=UTC
            - --minimum-age=0s
            - --grace-period=-1s
            - --metrics-address=
          resources:
            {}
          securityContext:
            runAsNonRoot: true
            runAsUser: 65534
            readOnlyRootFilesystem: true
            capabilities:
              drop: ["ALL"]
      serviceAccountName: "default"
